"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { Avatar, DevChip, FounderChip, RankBadge } from "@/components/ui";
import { ExpiryCountdown } from "@/components/expiry-countdown";
import { cn, type PublicUser } from "@/lib/utils";

interface DmMessage { id: number; content: string; createdAt: string; mine: boolean; editable?: boolean; }
const MAX_LEN = 400;
const EDIT_WINDOW_MS = 3 * 60 * 1000;
const REACTIONS = ["❤️", "😂", "🔥", "😭", "👍"];

export function DmThread({ me, other, sealed }: { me: PublicUser; other: PublicUser; sealed: boolean }) {
  const [messages, setMessages] = useState<DmMessage[]>([]);
  const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [connLost, setConnLost] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null); const [replyingTo, setReplyingTo] = useState<DmMessage | null>(null); const [activeMessageId, setActiveMessageId] = useState<number | null>(null); const [reactionPickerId, setReactionPickerId] = useState<number | null>(null); const [reactions, setReactions] = useState<Record<number, string>>({});
  const scrollerRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null); const lastIdRef = useRef(0); const stickRef = useRef(true);
  const poll = useCallback(async () => { try { const res = await fetch(`/api/dm/messages?with=${encodeURIComponent(other.username)}&after=${lastIdRef.current}`, { cache: "no-store" }); if (!res.ok) { setConnLost(true); return; } const data = await res.json(); setConnLost(false); if (data.sealed) return; const incoming = (data.messages ?? []) as DmMessage[]; if (incoming.length) { setMessages(prev => { const seen = new Set(prev.map(m => m.id)); return [...prev, ...incoming.filter(m => !seen.has(m.id))].slice(-200); }); lastIdRef.current = Math.max(lastIdRef.current, ...incoming.map(m => m.id)); } } catch { setConnLost(true); } }, [other.username]);
  useEffect(() => { if (sealed) return; poll(); const t = setInterval(poll, 3000); return () => clearInterval(t); }, [poll, sealed]);
  useEffect(() => { const el = scrollerRef.current; if (el && stickRef.current) el.scrollTop = el.scrollHeight; }, [messages]);
  function openActions(m: DmMessage) { setActiveMessageId(id => id === m.id ? null : m.id); setReactionPickerId(null); }
  function startReply(m: DmMessage) { setActiveMessageId(null); setReactionPickerId(null); setEditingId(null); setReplyingTo(m); inputRef.current?.focus(); }
  function startEdit(m: DmMessage) { if (!m.mine || Date.now() - new Date(m.createdAt).getTime() >= EDIT_WINDOW_MS) return; setActiveMessageId(null); setReactionPickerId(null); setReplyingTo(null); setEditingId(m.id); setInput(m.content.slice(0, MAX_LEN)); inputRef.current?.focus(); }
  function cancelAction() { setEditingId(null); setReplyingTo(null); setInput(""); inputRef.current?.focus(); }
  async function submit(e: React.FormEvent) { e.preventDefault(); const content = input.trim(); if (!content || busy) return; setBusy(true); setError(""); try { if (editingId !== null) { const res = await fetch("/api/dm/messages", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editingId, content }) }); const data = await res.json(); if (!res.ok) { setError(data.error ?? "Could not edit."); return; } setMessages(prev => prev.map(m => m.id === editingId ? data.message : m)); setEditingId(null); setInput(""); return; } const replyPrefix = replyingTo ? `↪ @${replyingTo.mine ? me.username : other.username}: "${replyingTo.content.slice(0, 180)}"\n` : ""; const res = await fetch("/api/dm/messages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: other.username, content: `${replyPrefix}${content}`.slice(0, MAX_LEN) }) }); const data = await res.json(); if (!res.ok) { setError(data.error ?? "Could not send."); return; } setReplyingTo(null); setInput(""); if (data.message) { setMessages(prev => [...prev.filter(m => m.id !== data.message.id), data.message].slice(-200)); lastIdRef.current = Math.max(lastIdRef.current, data.message.id); } } catch { setError("Network error — try again."); } finally { setBusy(false); inputRef.current?.focus(); } }
  if (sealed) return <div className="flex h-full flex-col items-center justify-center p-6 text-center"><span className="text-5xl">🔒</span><h1 className="mt-4 font-display text-2xl uppercase tracking-wide text-white">Channel <span className="text-fire">sealed</span></h1><p className="mt-3 max-w-sm text-sm leading-relaxed text-slate-400">A block seal sits between you two. No messages can cross it — lift the seal from their profile to open this channel again.</p><Link href={`/players/${encodeURIComponent(other.username)}`} className="clip-btn mt-6 bg-white/10 px-6 py-3 font-display text-xs uppercase tracking-widest text-white">view profile</Link></div>;
  return <div className="flex h-full flex-col bg-slate-900/40">
    <div className="flex items-center gap-2.5 border-b border-white/10 bg-slate-900/90 px-3 py-2.5"><Link href="/messages" className="text-xl text-slate-400">←</Link><Link href={`/players/${encodeURIComponent(other.username)}`} className="flex min-w-0 items-center gap-2.5"><Avatar name={other.username} color={other.avatarColor} size={38} dev={other.dev}/><span className="truncate font-display text-base uppercase text-white">{other.username}</span>{other.dev&&<DevChip size="xs"/>}{other.founder&&<FounderChip size="xs"/>}<RankBadge rank={other.rank} size="xs"/></Link></div>
    <div ref={scrollerRef} className="nice-scroll flex-1 space-y-3 overflow-y-auto px-3 py-4 sm:px-6">
      {messages.map(m => { const canEdit = m.mine && Date.now() - new Date(m.createdAt).getTime() < EDIT_WINDOW_MS; const active = activeMessageId === m.id; return <div key={m.id} className={cn("group flex", m.mine ? "justify-end" : "justify-start")}><div className="relative max-w-[85%] sm:max-w-[65%]">
        <div className={cn("relative flex items-center gap-1 rounded-xl px-1", m.mine ? "flex-row-reverse" : "flex-row")}>
          <div className={cn("clip-tag min-w-0 px-3.5 py-2.5", m.mine ? "bg-orange-400" : "bg-slate-800")} style={{WebkitUserSelect:"none",userSelect:"none",WebkitTouchCallout:"none"}}><p className={cn("whitespace-pre-wrap break-words text-[15px] leading-relaxed",m.mine?"text-slate-950":"text-slate-100")}>{m.content}</p><div className="mt-1 flex justify-end">{reactions[m.id]&&<span className="text-sm">{reactions[m.id]}</span>}<ExpiryCountdown createdAt={m.createdAt} vault={false}/></div></div>
          <button type="button" aria-label="Message actions" onClick={() => openActions(m)} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-white/10 bg-slate-950 text-base text-slate-300 shadow-lg">⋯</button>
        </div>
        {active && <div className={cn("absolute bottom-full z-30 mb-2 flex items-center gap-1 rounded-xl border border-white/10 bg-slate-950/95 p-1.5 shadow-2xl", m.mine ? "right-0" : "left-0")}><button type="button" onClick={() => setReactionPickerId(m.id)} className="rounded-lg px-2.5 py-2 text-xs font-bold text-white">❤️ React</button><button type="button" onClick={() => startReply(m)} className="rounded-lg px-2.5 py-2 text-xs font-bold text-white">↩ Reply</button>{canEdit&&<button type="button" onClick={() => startEdit(m)} className="rounded-lg px-2.5 py-2 text-xs font-bold text-white">✏️ Edit</button>}</div>}
        {reactionPickerId===m.id&&<div className="absolute bottom-full z-40 mb-12 flex gap-1 rounded-full border border-white/10 bg-slate-950/95 p-1.5 shadow-2xl">{REACTIONS.map(r=><button key={r} type="button" onClick={()=>{setReactions(p=>({...p,[m.id]:r}));setReactionPickerId(null);setActiveMessageId(null)}} className="px-2 py-1 text-lg">{r}</button>)}</div>}
      </div></div> })}
    </div>
    {connLost&&<div className="border-t border-amber-500/40 bg-amber-950/40 px-4 py-2 text-xs text-amber-300">📡 the line wobbled — retrying…</div>}
    {(editingId!==null||replyingTo)&&<div className="flex items-center gap-2 border-t border-orange-500/20 bg-orange-950/20 px-3 py-2"><span className="font-hud text-[10px] font-bold uppercase tracking-wider text-orange-300">{editingId!==null?"editing message":`replying to ${replyingTo?.mine?me.username:other.username}`}</span><button type="button" onClick={cancelAction} className="ml-auto text-[10px] uppercase text-slate-400">cancel</button></div>}
    {error&&<div className="border-t border-rose-500/40 bg-rose-950/50 px-4 py-2 text-xs text-rose-300">{error}</div>}
    <form onSubmit={submit} className="flex gap-2 border-t border-white/10 bg-slate-900/90 p-2.5"><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value.slice(0,MAX_LEN))} placeholder={editingId!==null?"Edit your message…":`Message ${other.username}…`} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-950/70 px-4 py-2.5 text-base text-white"/><button type="submit" disabled={busy||!input.trim()} className="clip-btn bg-gradient-to-r from-orange-500 to-amber-400 px-6 py-2.5 font-display text-xs uppercase text-slate-950">{busy?"…":editingId!==null?"Save →":"Send →"}</button></form>
  </div>;
}
